services:
  containarr:
    image: containarr
    container_name: containarr
    volumes:
      - ./volumes/containarr:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    networks:
      - containarr

networks:
  containarr:
    name: containarr
    driver: bridge
