services:
  containarr:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run serve
    # environment:
    # - CONTAINARR_DEMO_MODE=true
    # - CONTAINARR_VERSION=0.0.0-dev
    # - LETS_ENCRYPT_DIRECTORY_URL=https://acme-staging-v02.api.letsencrypt.org/directory
    volumes:
      - ./lib/:/app/lib/
      - ./services/:/app/services/
      - ./server.mjs:/app/server.mjs
      - ./config.mjs:/app/config.mjs
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
